[all]
control-plane  ansible_host=10.0.20.72  ip=10.0.20.72  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/tantai/.ssh/id_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@18.142.115.189"'
worker-1       ansible_host=10.0.20.239  ip=10.0.20.239  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/tantai/.ssh/id_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@18.142.115.189"'
worker-2       ansible_host=10.0.20.209  ip=10.0.20.209  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/tantai/.ssh/id_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@18.142.115.189"'
worker-3       ansible_host=10.0.20.183  ip=10.0.20.183  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/tantai/.ssh/id_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@18.142.115.189"'

[kube_control_plane]
control-plane

[etcd]
control-plane

[kube_node]
worker-1
worker-2
worker-3

[k8s_cluster:children]
kube_control_plane
kube_node

[calico_rr]
