kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
    - "argocd.tools.votantai.me"
  pathPrefixes:
    - /
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-server
    service: argocd-server
    port: 80
  replicas:
    min: 1
    max: 1
  scaledownPeriod: 300
