[all]
control-plane-1  ansible_host=10.0.20.32  ip=10.0.20.32  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.250.58.97'
worker-1  ansible_host=10.0.20.108  ip=10.0.20.108  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.250.58.97'
worker-2  ansible_host=10.0.20.142  ip=10.0.20.142  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.250.58.97'
worker-3  ansible_host=10.0.20.106  ip=10.0.20.106  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.250.58.97'
apps-worker-1  ansible_host=10.0.20.15  ip=10.0.20.15  ansible_user=ubuntu  ansible_ssh_private_key_file=/home/tantai/.ssh/id_ed25519  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.250.58.97'

[kube_control_plane]
control-plane-1

[etcd]
control-plane-1

[kube_node]
worker-1
worker-2
worker-3
apps-worker-1

[k8s_cluster:children]
kube_control_plane
kube_node

[apps_workers]
apps-worker-1

[calico_rr]
