#!/bin/bash
# Full Kubespray setup: clone, configure, and deploy Kubernetes (HA mode)
# Run from project root: bash platform/kubespray/run-kubespray.sh
# Prerequisites: python3, pip3, ssh key at ~/.ssh/id_ed25519

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# kubespray-src and .venv live in kubespray/ (large — excluded from git)
KUBESPRAY_DIR="${PROJECT_ROOT}/kubespray/kubespray-src"
VENV_BASE="${PROJECT_ROOT}/kubespray"
K8S_VERSION="v1.29.5"

# ── 1. Generate inventory from Terraform outputs ──────────────────────────────
echo "==> Generating inventory..."
bash "$SCRIPT_DIR/generate-inventory.sh"

# Read IPs from Terraform infra directory
BASTION_IP=$(cd "${PROJECT_ROOT}/infra/aws/envs/tools" && terraform output -raw bastion_public_ip)
NLB_DNS=$(cd "${PROJECT_ROOT}/infra/aws/envs/tools" && terraform output -raw api_nlb_dns)
CONTROL_PLANE_IPS=$(cd "${PROJECT_ROOT}/infra/aws/envs/tools" && terraform output -json control_plane_private_ips | tr -d '[]" ' | tr ',' '\n')
FIRST_CP=$(echo "$CONTROL_PLANE_IPS" | head -1)

# Build supplementary_addresses list (all control plane IPs)
SUPPLEMENTARY_ADDRESSES=""
while IFS= read -r IP; do
  SUPPLEMENTARY_ADDRESSES+="  - ${IP}"$'\n'
done < <(echo "$CONTROL_PLANE_IPS")

# ── 2. Clone Kubespray ────────────────────────────────────────────────────────
if [ ! -d "$KUBESPRAY_DIR" ]; then
  echo "==> Cloning Kubespray..."
  git clone --depth 1 --branch release-2.25 \
    https://github.com/kubernetes-sigs/kubespray.git "$KUBESPRAY_DIR"
else
  echo "==> Kubespray already cloned at $KUBESPRAY_DIR"
fi

# ── 3. Install Python dependencies ───────────────────────────────────────────
VENV_DIR="${VENV_BASE}/.venv"

if [ ! -f "$VENV_DIR/bin/pip" ]; then
  echo "==> Installing python3-venv..."
  sudo apt-get install -y python3-venv python3-full
  rm -rf "$VENV_DIR"
  echo "==> Creating Python virtual environment..."
  python3 -m venv "$VENV_DIR"
fi

echo "==> Installing Ansible and dependencies..."
"$VENV_DIR/bin/pip" install -r "$KUBESPRAY_DIR/requirements.txt"

# ── 4. Copy sample inventory ──────────────────────────────────────────────────
INVENTORY_DIR="$KUBESPRAY_DIR/inventory/devsecops"
mkdir -p "$INVENTORY_DIR"

cp -r "$KUBESPRAY_DIR/inventory/sample/group_vars" "$INVENTORY_DIR/"
cp "$SCRIPT_DIR/inventory.ini" "$INVENTORY_DIR/hosts.ini"  # generated by generate-inventory.sh

# ── 5. Set cluster variables ──────────────────────────────────────────────────
cat > "$INVENTORY_DIR/group_vars/k8s_cluster/k8s-cluster.yml" <<EOF
kube_version: ${K8S_VERSION}
kube_network_plugin: calico
kube_service_addresses: 10.96.0.0/12
kube_pods_subnet: 192.168.0.0/16
kube_proxy_mode: ipvs
container_manager: containerd
kubeconfig_localhost: true
kubectl_localhost: true

# HA: include all control plane IPs + NLB DNS in API server cert SANs
supplementary_addresses_in_ssl_keys:
${SUPPLEMENTARY_ADDRESSES}  - ${NLB_DNS}
EOF

# ── 6. Set HA loadbalancer ────────────────────────────────────────────────────
# Use localhost load balancer — Kubespray sets up nginx on each node pointing
# to all control planes. Avoids AWS internal NLB hairpin issue where instances
# can't reach an NLB they are registered as targets of.
cat >> "$INVENTORY_DIR/group_vars/all/all.yml" <<EOF

loadbalancer_apiserver_localhost: true
loadbalancer_apiserver_port: 6443
EOF

# ── 7. Run Kubespray playbook ─────────────────────────────────────────────────
echo "==> Running Kubespray cluster.yml — this takes 20-30 minutes for HA..."

cd "$KUBESPRAY_DIR"

export ANSIBLE_ROLES_PATH="$KUBESPRAY_DIR/roles"
export ANSIBLE_COLLECTIONS_PATH="$KUBESPRAY_DIR/collections"
export ANSIBLE_HOST_KEY_CHECKING=False

# Use cluster.yml for fresh install, scale.yml to add nodes to existing cluster
PLAYBOOK="${KUBESPRAY_PLAYBOOK:-cluster.yml}"
echo "==> Running playbook: $PLAYBOOK"

"$VENV_DIR/bin/ansible-playbook" \
  -i "$INVENTORY_DIR/hosts.ini" \
  --private-key="$HOME/.ssh/id_ed25519" \
  --become \
  --timeout=60 \
  -e 'ansible_become_method=sudo' \
  "$PLAYBOOK" \
  -v

echo ""
echo "==> Kubernetes HA cluster is ready!"

# ── 8. Fetch kubeconfig (from first control plane) ────────────────────────────
KUBECONFIG_FILE="$HOME/.kube/config"
mkdir -p "$HOME/.kube"
echo "==> Fetching kubeconfig from control-plane-1 via bastion..."
ssh -i "$HOME/.ssh/id_ed25519" \
  -o StrictHostKeyChecking=no \
  -o ProxyJump="ubuntu@${BASTION_IP}" \
  "ubuntu@${FIRST_CP}" \
  "sudo cat /etc/kubernetes/admin.conf" > "$KUBECONFIG_FILE"

# Point kubectl at localhost tunnel (always access via connect.sh)
sed -i "s|https://.*:6443|https://127.0.0.1:6443|g" "$KUBECONFIG_FILE"
chmod 600 "$KUBECONFIG_FILE"
# Skip TLS verify — cert is issued for cluster IPs, not 127.0.0.1
kubectl config set-cluster \
  "$(kubectl --kubeconfig "$KUBECONFIG_FILE" config view --minify -o jsonpath='{.clusters[0].name}')" \
  --insecure-skip-tls-verify=true \
  --kubeconfig "$KUBECONFIG_FILE"
echo "==> Kubeconfig saved to $KUBECONFIG_FILE (server: 127.0.0.1:6443)"

# ── 9. Install Helm ───────────────────────────────────────────────────────────
if ! command -v helm &>/dev/null; then
  echo "==> Installing Helm..."
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi

# ── 10. Install AWS EBS CSI driver + StorageClass ─────────────────────────────
echo "==> Installing AWS EBS CSI driver..."
helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
helm repo update
helm upgrade --install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
  --namespace kube-system --wait

kubectl apply -f - <<YAML
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
YAML

echo ""
echo "============================================================"
echo " HA Cluster ready!"
echo " Bastion:       ${BASTION_IP}"
echo " NLB endpoint:  ${NLB_DNS}:6443"
echo " Control planes: $(echo "$CONTROL_PLANE_IPS" | tr '\n' ' ')"
echo ""
echo " Run: ./connect.sh"
echo " Then: kubectl get nodes"
echo "============================================================"
