image:
  repository: library/productcatalogservice
  tag: "32"
  pullSecret: harbor-credentials
  harborImage: true
port:
  container: 3550
  service: 3550
probe:
  type: grpc
  initialDelaySeconds: 10
  periodSeconds: 10
env:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"
canary:
  enabled: true
  trafficRouting:
    enabled: false
  steps:
    - setWeight: 20
    - pause:
        duration: 30s
    - setWeight: 100
