image:
  repository: redis
  tag: "alpine"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

port:
  container: 6379
  service: 6379

probe:
  type: tcp             # redis uses TCP socket probe
  initialDelaySeconds: 5
  periodSeconds: 5

resources:
  requests:
    cpu: "70m"
    memory: "200Mi"
  limits:
    cpu: "125m"
    memory: "256Mi"
