{{- if .Values.canary.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ include "microservice.fullImage" . }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.port.container }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if ne .Values.probe.type "none" }}
          readinessProbe:
            {{- include "microservice.probe" . | nindent 12 }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
          livenessProbe:
            {{- include "microservice.probe" . | nindent 12 }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
          {{- end }}
  strategy:
    canary:
      {{- if .Values.canary.trafficRouting.enabled }}
      canaryService: {{ .Release.Name }}-canary
      stableService: {{ .Release.Name }}
      trafficRouting:
        nginx:
          stableIngress: {{ .Release.Name }}
      {{- end }}
      steps:
        {{- if .Values.canary.analysis.enabled }}
        - setWeight: 20
        - analysis:
            templates:
              - templateName: {{ .Release.Name }}-success-rate
        - setWeight: 50
        - pause:
            duration: 10m
        - setWeight: 80
        - pause:
            duration: 5m
        {{- else }}
        {{- toYaml .Values.canary.steps | nindent 8 }}
        {{- end }}
{{- end }}
